name: neo-inu

services:
  dev:
    container_name: neo-inu-dev
    image: neo-inu-dev
    build: .
    volumes:
      - ./cmd:/go/src/neo-inu/cmd
      - ./src:/go/src/neo-inu/src
    environment:
      TOKEN: ${TOKEN}
      RMCMD: true
      GUILD: ${GUID}

  prod:
    container_name: neo-inu-prod
    image: neo-inu-prod
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    environment:
      TOKEN: ${TOKEN}
      RMCMD: true
      GUILD: ${GUID}
