name: neo-inu

services:
  dev:
    container_name: neo-inu-dev
    image: neo-inu-dev
    build: .
    volumes:
      - ./cmd:/go/src/neo-inu/cmd
      - ./pkg:/go/src/neo-inu/pkg
      - ./internal:/go/src/neo-inu/internal
    env_file: .env

  prod:
    container_name: neo-inu-prod
    image: neo-inu-prod
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    env_file: .env
