FROM golang:1.24.1-alpine3.21 as builder
WORKDIR /go/src/neo-inu
COPY go.mod go.sum ./
RUN go mod download && go mod verify
COPY . .
RUN go build ./cmd/neo-inu/

FROM alpine:3.21
RUN apk add --no-cache ca-certificates
WORKDIR /neo-inu
COPY --from=builder /go/src/neo-inu/neo-inu .
CMD ["./neo-inu"]
